In [1065]:
import numpy as np
from scipy.stats import norm
import pandas as pd

In [1066]:
df=pd.read_csv('price_timeseries_30d_WETH_USDT.csv', sep=',')

In [1067]:
df

Unnamed: 0        date    token_0   token_1     total_gas  swap_price
0            0  2022-05-27  1767.3271  1.025759  4.961605e+06    8.768779
1            1  2022-05-28  1769.6007  0.985839  8.493774e+06   15.030589
2            2  2022-05-29  1790.8622  0.987865  8.236613e+06   14.750638
3            3  2022-05-30  1852.2931  0.929358  3.173705e+06    5.878632
4            4  2022-05-31  1941.7574  0.995631  3.747930e+06    7.277571
5            5  2022-06-01  1952.1045  1.068347  8.037165e+06   15.689385
6            6  2022-06-02  1794.1923  0.979493  5.985370e+06   10.738906
7            7  2022-06-03  1821.4354  1.026002  1.145593e+07   20.866243
8            8  2022-06-04  1796.8967  0.996102  5.831310e+07  104.782608
9            9  2022-06-05  1803.2993  0.998038  5.816242e+06   10.488425
10          10  2022-06-06  1772.2766  0.953944  4.441263e+06    7.871147
11          11  2022-06-07  1825.7062  1.004935  9.054057e+06   16.530047
12          12  2022-06-08  1855.2657  1.034828  1.174332e+07   21.786981
13          13  2022-06-09  1796.4103  1.003985  8.753360e+06   15.724626
14          14  2022-06-10  1721.5367  1.034976  1.728859e+07   29.762950
15          15  2022-06-11  1568.2997  1.025667  5.734616e+06    8.993597
16          16  2022-06-12  1532.5399  1.057649  7.217582e+06   11.061232
17          17  2022-06-13  1430.3357  1.194282  5.840339e+06    8.353645
18          18  2022-06-14  1230.8961  1.014231  8.272014e+06   10.181990
19          19  2022-06-15  1217.1380  0.989172  4.010210e+06    4.880979
20          20  2022-06-16  1178.6075  1.094692  1.064918e+07   12.551207
21          21  2022-06-17  1083.2830  0.997373  7.868157e+06    8.523441
22          22  2022-06-18  1071.1492  1.076473  5.510882e+06    5.902977
23          23  2022-06-19  1045.7607  0.928943  2.578953e+06    2.696968
24          24  2022-06-20  1124.3110  0.991763  3.869972e+06    4.351052
25          25  2022-06-21  1120.6864  0.997994  3.119580e+06    3.496071
26          26  2022-06-22  1090.4065  1.030078  6.961752e+06    7.591140
27          27  2022-06-23  1084.2496  0.947421  6.978386e+06    7.566312
28          28  2022-06-24  1221.0493  0.984750  8.116172e+06    9.910247
29          29  2022-06-25  1250.3524  0.999854  4.612824e+06    5.767656
30          30  2022-06-26  1229.0845  0.998898  4.208130e+06    5.172148

In [1068]:
q_x = df["token_0"].values[-1]
q_y = df["token_1"].values[-1]
K = 1.2888929e+16
n_days = 29
n_edays = 29
T_x = 1000000

In [1069]:
K

1.2888929e+16

In [1070]:
quotes = np.zeros((n_days,2))
quotes[:,0] = df["token_0"].values[:-2]
quotes[:,1] = df["token_1"].values[:-2]
#first column DAI, second column USDC

In [1071]:
quotes

array([[1.7673271e+03, 1.0257589e+00],
       [1.7696007e+03, 9.8583880e-01],
       [1.7908622e+03, 9.8786470e-01],
       [1.8522931e+03, 9.2935765e-01],
       [1.9417574e+03, 9.9563080e-01],
       [1.9521045e+03, 1.0683466e+00],
       [1.7941923e+03, 9.7949326e-01],
       [1.8214354e+03, 1.0260017e+00],
       [1.7968967e+03, 9.9610200e-01],
       [1.8032993e+03, 9.9803805e-01],
       [1.7722766e+03, 9.5394444e-01],
       [1.8257062e+03, 1.0049353e+00],
       [1.8552657e+03, 1.0348280e+00],
       [1.7964103e+03, 1.0039847e+00],
       [1.7215367e+03, 1.0349759e+00],
       [1.5682997e+03, 1.0256668e+00],
       [1.5325399e+03, 1.0576488e+00],
       [1.4303357e+03, 1.1942824e+00],
       [1.2308961e+03, 1.0142306e+00],
       [1.2171380e+03, 9.8917234e-01],
       [1.1786075e+03, 1.0946925e+00],
       [1.0832830e+03, 9.9737275e-01],
       [1.0711492e+03, 1.0764731e+00],
       [1.0457607e+03, 9.2894260e-01],
       [1.1243110e+03, 9.9176335e-01],
       [1.1206864e+03, 9.

In [1072]:
pools = np.zeros((n_days,2))
pools[:,0] = np.sqrt(K * quotes[:,0]/(quotes[:,1]))
pools[:,1] = np.sqrt(K * quotes[:,1]/quotes[:,0])

In [1073]:
pools

array([[4.71242268e+09, 2.73509612e+06],
       [4.80997814e+09, 2.67962319e+06],
       [4.83382326e+09, 2.66640469e+06],
       [5.06841107e+09, 2.54299204e+06],
       [5.01368147e+09, 2.57075147e+06],
       [4.85292814e+09, 2.65590765e+06],
       [4.85894725e+09, 2.65261760e+06],
       [4.78345026e+09, 2.69448375e+06],
       [4.82189851e+09, 2.67299881e+06],
       [4.82579393e+09, 2.67084115e+06],
       [4.89342151e+09, 2.63392985e+06],
       [4.83899095e+09, 2.66355716e+06],
       [4.80703615e+09, 2.68126317e+06],
       [4.80228175e+09, 2.68391770e+06],
       [4.63021801e+09, 2.78365489e+06],
       [4.43935419e+09, 2.90333423e+06],
       [4.32159008e+09, 2.98245061e+06],
       [3.92892636e+09, 3.28052191e+06],
       [3.95503889e+09, 3.25886277e+06],
       [3.98237676e+09, 3.23649162e+06],
       [3.72517727e+09, 3.45995051e+06],
       [3.74154205e+09, 3.44481736e+06],
       [3.58122666e+09, 3.59902632e+06],
       [3.80916806e+09, 3.38365984e+06],
       [3.822501

In [1074]:
# rf=np.ones((n_days,2))
# rf[:,0] = 0.1 / 365
# rf[:,0] = 0.15 / 365

In [1075]:
gas = df["swap_price"].values[:-2]

In [1076]:
gas_bar = np.mean(gas) 

In [1077]:
gas_bar

14.207185667734999

In [1078]:
r = np.zeros((n_days-1,2))
r[:,0] = (quotes[1:n_days,0] - quotes[0:n_days - 1,0])/ quotes[0:n_days - 1,0]
r[:,1] = (quotes[1:n_days,1] - quotes[0:n_days - 1,1])/ quotes[0:n_days - 1,1]

In [1079]:
r

array([[ 0.00128646, -0.03891762],
       [ 0.01201486,  0.002055  ],
       [ 0.03430242, -0.05922577],
       [ 0.04829921,  0.07131071],
       [ 0.00532873,  0.0730349 ],
       [-0.08089331, -0.08316902],
       [ 0.01518405,  0.04748214],
       [-0.01347218, -0.02914196],
       [ 0.00356314,  0.00194363],
       [-0.0172033 , -0.04418029],
       [ 0.03014744,  0.05345265],
       [ 0.01619072,  0.0297459 ],
       [-0.03172343, -0.02980524],
       [-0.04167957,  0.0308682 ],
       [-0.08901175, -0.00899451],
       [-0.02280164,  0.03118167],
       [-0.06668942,  0.12918617],
       [-0.13943552, -0.15076149],
       [-0.0111773 , -0.02470667],
       [-0.03165664,  0.1066752 ],
       [-0.08087892, -0.08890145],
       [-0.01120095,  0.07930871],
       [-0.02370211, -0.13704987],
       [ 0.07511307,  0.06762608],
       [-0.00322384,  0.00628209],
       [-0.02701907,  0.0321488 ],
       [-0.00564643, -0.08024353],
       [ 0.12616993,  0.03940044]])

In [1080]:
mu_x, std_x = norm.fit(r[:,0])
mu_y, std_y = norm.fit(r[:,1])

In [1081]:
mu_x, std_x

(-0.011779119521677737, 0.051408570601321917)

In [1082]:
e_p = np.zeros((n_edays,2)) 

for i in range(n_edays): 
    e_p[i,0] = 1
    e_p[i,1] = q_y * (np.exp((mu_y + 0.5 * std_y**2)*i)) 

In [1083]:
e_pools = np.zeros((n_edays,2))
e_pools[:,0] = np.sqrt(K / (e_p[:,1]/e_p[:,0]))
e_pools[:,1] = np.sqrt(K / (e_p[:,0]/e_p[:,1]))

In [1084]:
e_pools

array([[1.13592027e+08, 1.13466845e+08],
       [1.13404284e+08, 1.13654692e+08],
       [1.13216851e+08, 1.13842850e+08],
       [1.13029728e+08, 1.14031319e+08],
       [1.12842914e+08, 1.14220100e+08],
       [1.12656409e+08, 1.14409194e+08],
       [1.12470212e+08, 1.14598601e+08],
       [1.12284323e+08, 1.14788322e+08],
       [1.12098741e+08, 1.14978356e+08],
       [1.11913466e+08, 1.15168705e+08],
       [1.11728497e+08, 1.15359369e+08],
       [1.11543834e+08, 1.15550349e+08],
       [1.11359476e+08, 1.15741645e+08],
       [1.11175423e+08, 1.15933258e+08],
       [1.10991674e+08, 1.16125188e+08],
       [1.10808229e+08, 1.16317436e+08],
       [1.10625086e+08, 1.16510002e+08],
       [1.10442247e+08, 1.16702886e+08],
       [1.10259710e+08, 1.16896091e+08],
       [1.10077474e+08, 1.17089615e+08],
       [1.09895540e+08, 1.17283459e+08],
       [1.09713906e+08, 1.17477624e+08],
       [1.09532572e+08, 1.17672111e+08],
       [1.09351539e+08, 1.17866920e+08],
       [1.091708

In [1085]:
e_p

array([[1.        , 0.99889797],
       [1.        , 1.0022081 ],
       [1.        , 1.0055292 ],
       [1.        , 1.00886131],
       [1.        , 1.01220445],
       [1.        , 1.01555868],
       [1.        , 1.01892402],
       [1.        , 1.02230052],
       [1.        , 1.0256882 ],
       [1.        , 1.02908711],
       [1.        , 1.03249728],
       [1.        , 1.03591875],
       [1.        , 1.03935156],
       [1.        , 1.04279575],
       [1.        , 1.04625134],
       [1.        , 1.04971839],
       [1.        , 1.05319693],
       [1.        , 1.056687  ],
       [1.        , 1.06018863],
       [1.        , 1.06370187],
       [1.        , 1.06722674],
       [1.        , 1.0707633 ],
       [1.        , 1.07431158],
       [1.        , 1.07787161],
       [1.        , 1.08144345],
       [1.        , 1.08502712],
       [1.        , 1.08862266],
       [1.        , 1.09223012],
       [1.        , 1.09584953]])

In [1086]:
totalEstimatedPrice = np.zeros((n_edays,1)) 

In [1087]:
def priceIntegral(j,i): 
    #yo = (1 / (3 * K)) * (e_pools[j,0]**3 - (e_pools[j,0] - (T_x / i))**3) * e_p[j,1]
    yo = (K) * ((1/(e_pools[j,0] - (T_x / i))) - (1 / e_pools[j,0])) / e_p[j,1]
    print(yo)
    return (yo)

In [1088]:
for i in range(1,n_edays): 
    for j in range(i):
        totalEstimatedPrice[i,0] += (priceIntegral(j,i)) + gas_bar 

1008881.6235424513
502210.5890756202
502214.2649596937
334314.37158531236
334316.0005028775
334317.6321330368
250551.42828755805
250552.3432057272
250553.25964524507
250554.1776086656
200352.75848723014
200353.34351815606
200353.92952100627
200354.51649746174
200355.10444910094
166911.56584647685
166911.97187899525
166912.3785856834
166912.78596766677
166913.19402608226
166913.60276205363
143037.03102419648
143037.32920849713
143037.62788768383
143037.9270626031
143038.22673407756
143038.5269029131
143038.82756994682
125137.70520279609
125137.9334282541
125138.16203235833
125138.39101575818
125138.62037910197
125138.85012298748
125139.08024808086
125139.31075498239
111219.90190546613
111220.08218756245
111220.26276871005
111220.443649392
111220.62483013884
111220.80631142078
111220.98809375145
111221.17017758034
111221.35256347868
100088.11191624559
100088.25791612604
100088.40415814004
100088.55064270836
100088.69737020093
100088.84434104504
100088.99155562237
100089.13901435494
10008

In [1089]:
totalEstimatedPrice

array([[      0.        ],
       [1008895.83072812],
       [1004453.26840665],
       [1002990.62577823],
       [1002268.03748987],
       [1001840.68840129],
       [1001560.74218096],
       [1001364.94668959],
       [1001221.71066966],
       [1001113.49715851],
       [1001029.79015464],
       [1000963.90071706],
       [1000911.37118738],
       [1000869.1164234 ],
       [1000834.93330608],
       [1000807.20655958],
       [1000784.72494887],
       [1000766.56238338],
       [1000751.9986708 ],
       [1000740.46530854],
       [1000731.50754478],
       [1000724.75728273],
       [1000719.91337991],
       [1000716.72708575],
       [1000714.99112406],
       [1000714.53139353],
       [1000715.20058756],
       [1000716.87322956],
       [1000719.4417741 ]])

In [1090]:
def main():
    for i in range(1,n_edays): 
        for j in range(i):
            totalEstimatedPrice[i,0] += (priceIntegral(j,i)) + gas_bar 
    

if __name__ == "__main__":
    main()

1008881.6235424513
502210.5890756202
502214.2649596937
334314.37158531236
334316.0005028775
334317.6321330368
250551.42828755805
250552.3432057272
250553.25964524507
250554.1776086656
200352.75848723014
200353.34351815606
200353.92952100627
200354.51649746174
200355.10444910094
166911.56584647685
166911.97187899525
166912.3785856834
166912.78596766677
166913.19402608226
166913.60276205363
143037.03102419648
143037.32920849713
143037.62788768383
143037.9270626031
143038.22673407756
143038.5269029131
143038.82756994682
125137.70520279609
125137.9334282541
125138.16203235833
125138.39101575818
125138.62037910197
125138.85012298748
125139.08024808086
125139.31075498239
111219.90190546613
111220.08218756245
111220.26276871005
111220.443649392
111220.62483013884
111220.80631142078
111220.98809375145
111221.17017758034
111221.35256347868
100088.11191624559
100088.25791612604
100088.40415814004
100088.55064270836
100088.69737020093
100088.84434104504
100088.99155562237
100089.13901435494
10008